version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: patient_transport_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54322:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  back-end:
    build: .
    container_name: backend_container
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - .:/app

volumes:
  pgdata:
